-- ********************************script 1**************************

local current =
redis.call(
        'INCR',
        KEYS[1]
)

if current == 1 then
    redis.call(
            'EXPIRE',
            KEYS[1],
            ARGV[1]
    )
end

return current

-- *****************************************Line 1 - 5******************************************
--local current =
--    Creates a local Lua variable.
--    Think of it like Java.
--    int current; or long current;

--redis.call('INCR',KEYS[1])
--    This executes INCR key inside Redis.
--    Suppose
--        KEYS[1] = login:user123
--        Redis executes
--        INCR login:user123
    --Example 1
    --    Before
    --        login:user123 = doesn't exist
    --    Run
    --        INCR login:user123
    --        Redis creates
    --        login:user123 = 1
    --        Returns 1
    --    So now
    --        current = 1
    --
    --Example 2
    --    Before
    --        login:user123 = 4(count)
    --    Run
    --        INCR login:user123
    --        Now
    --        login:user123 = 5
    --        Returns 5
    --    So now
    --        current = 5

--Therefore
--    local current =
--    redis.call('INCR', KEYS[1])
--means
--    Increase the counter
--    Store the new value inside current

-- *****************************************Line 1 - 5******************************************

-- *****************************************Line 7 - 15******************************************

--if current == 1 then
--    This means Was this key created just now?
--    Remember INCR returns new value
--    If new value is 1 it means The key did not exist before.
--        Example
--            Before
--                login:user123 doesn't exist
--            After
--                INCR becomes 1
--                So current == 1

--redis.call( 'EXPIRE', KEYS[1], ARGV[1] )
--    Runs
--        EXPIRE login:user123 60
--    Suppose
--        ARGV[1]=60 Now Redis sets TTL = 60 sec

--Why only when current == 1?
--    Suppose login attempts
--    First request
--        INCR value = 1 EXPIRE = 60 sec
--        Now login:user123 Value = 1 TTL = 60 sec
--    Second request after 10 sec
--        INCR Value = 2 TTL becomes 50 sec remaining
--        No need to reset TTL.
--    Third request Value = 3 TTL = 45 sec
--
--Without LUA Script if current == 1
--    Suppose every request does EXPIRE 60
--
--Timeline
--    t=0
--        counter=1 TTL=60
--    t=20
--        counter=2 TTL reset to 60
--    t=40
--        counter=3 TTL reset again
--
--The key never expires if requests keep coming.
--That breaks most rate-limiting algorithms because the time window keeps extending.

--Step 5 return current
--    Returns 1 or 2 or 15 to your Java application.

-- *****************************************Line 7 - 15******************************************

--Complete Example
--    Request 1 INCR
--        returns 1 Set TTL 60 sec
--    Request 2 INCR
--        returns 2 TTL remains 55 sec
--    Request 3 INCR
--        returns 3 TTL remains 40 sec
--    After 60 seconds
--        Redis automatically deletes login:user123
--    Next request INCR
--        creates 1 Again.

--Why use a Lua script?
--    Without Lua, you might do:
--        Long current = redisTemplate.opsForValue().increment(key);
--        if (current == 1) {
--        redisTemplate.expire(key, 60, TimeUnit.SECONDS);
--        }
--This is not atomic. Imagine two clients:
--    Client A runs INCR and gets 1. Before Client A can call EXPIRE, the application crashes. The key is left with no TTL and never expires.
--    By putting both commands in a Lua script, Redis executes them as one atomic unit, so the counter and its expiry are always set together.

--Script 2
--    if redis.call( 'GET', KEYS[1]) == ARGV[1]
--    then
--        return redis.call('DEL',KEYS[1])
--    else
--        return 0
--    end
--
--This is one of the most famous Redis Lua scripts. It is used to safely release a distributed lock.
--Suppose your lock key is
--    lock:product:101
--        Its value is abc123
--            where abc123 is a unique token (UUID) generated by the client that acquired the lock.
--
--Step 1
--    redis.call('GET',KEYS[1])
--    Executes --> GET lock:product:101
--    Suppose Redis returns abc123
--Step 2 == ARGV[1]
--    Suppose ARGV[1] = abc123
--    So GET == abc123
--    is true.
--
--Step 3
--    return redis.call('DEL',KEYS[1])
--    Runs DEL lock:product:101
--    Deletes the lock.
--    Returns 1
--Else Suppose Redis contains xyz999 but your application sends abc123 Then abc123 != xyz999
--    So return 0 Nothing is deleted.
--Why not simply do DEL?
--    Imagine this sequence:
--        Thread A acquires lock
--        Value = token-A TTL = 30 sec
--        Thread A starts working. It takes longer than 30 seconds. The lock expires automatically.
--        Now: lock key is gone Thread B acquires the same lock.
--        Value = token-B Thread B is now the rightful owner.
--
--    Thread A finally finishes and blindly executes: redisTemplate.delete("lock:product:101");
--    It deletes Thread B's lock, even though Thread A no longer owns it.
--
--    Now another thread could acquire the lock while Thread B is still working, breaking mutual exclusion.
--    Using the Lua script prevents this:
--
--    GET lock:product:101
--        returns token-B
--        Thread A sends token-A
--        Comparison fails. token-B != token-A
--        Redis does not delete the key.
--        Thread B keeps its lock safely.
--
--    Why is this Lua script considered "better"? A common but incorrect approach is:
--        if (redisTemplate.opsForValue().get(key).equals(token)) {
--        redisTemplate.delete(key);
--        }
--    The problem is that GET and DEL are two separate Redis commands. A race condition can occur:
--        Thread A executes GET and sees token-A.
--        Before it sends DEL, the lock expires.
--        Thread B acquires the lock with token-B.
--        Thread A executes DEL, accidentally deleting Thread B's lock.
--
--    The Lua script combines GET and DEL into a single atomic operation inside Redis.
--    No other client can modify the key between those two commands, making it the correct way to release a distributed lock.